/*
 * Generates src/styles/colors.generated.css and src/styleguide/colors.generated.json
 * from tokens/color.mjs, then verifies every declared contrast pair in every mode.
 * Exits non-zero if any pair fails, so a bad palette never reaches a component.
 */
import { writeFileSync } from "node:fs";
import { primitives, roles, modeRoles, pairs } from "../tokens/color.mjs";

const MODES = Object.keys(modeRoles);

/* ── WCAG 2.x contrast ──────────────────────────────────────────────────── */
const channels = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const luminance = (hex) => {
  const [r, g, b] = channels(hex).map((v) => v / 255)
    .map((v) => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
};
/* Alpha-composite white over a colour. */
const lift = (hex, alpha) => "#" + channels(hex)
  .map((v) => Math.round(255 * alpha + v * (1 - alpha)).toString(16).padStart(2, "0"))
  .join("").toUpperCase();

/* ── validate references ────────────────────────────────────────────────── */
const allRefs = [...Object.values(roles), ...MODES.flatMap((m) => Object.values(modeRoles[m]))];
for (const ref of allRefs) {
  if (!primitives[ref]) throw new Error(`Role references unknown primitive "${ref}"`);
}
const modeRoleNames = new Set(Object.keys(modeRoles.DATA));
const resolve = (role, mode) => {
  if (modeRoleNames.has(role)) return primitives[modeRoles[mode][role]];
  if (!roles[role]) throw new Error(`Pair references unknown role "${role}"`);
  return primitives[roles[role]];
};

/* ── contrast gate ──────────────────────────────────────────────────────── */
const report = [];
let failures = 0;
for (const [fg, bg, min, opts = {}] of pairs) {
  const usesMode = modeRoleNames.has(fg) || modeRoleNames.has(bg);
  for (const mode of usesMode ? MODES : ["—"]) {
    const m = mode === "—" ? "DATA" : mode;
    const back = opts.lift ? lift(resolve(bg, m), opts.lift) : resolve(bg, m);
    const ratio = contrast(resolve(fg, m), back);
    const pass = ratio >= min;
    if (!pass) failures++;
    report.push({ mode, fg, bg: opts.lift ? `${bg} + ${opts.lift * 100}% white` : bg,
      min, ratio: Math.round(ratio * 100) / 100, pass });
  }
}

/* ── emit CSS ───────────────────────────────────────────────────────────── */
const used = [...new Set(allRefs)].sort();
const css = `/* GENERATED by scripts/build-tokens.mjs from tokens/color.mjs — do not edit. */

/* Tier 1 · primitives. Never referenced by components. */
:root {
${used.map((ref) => `  --prim-${ref}: ${primitives[ref]};`).join("\n")}
}

/* Tier 2 · roles. */
:root {
  color-scheme: light;
${Object.entries(roles).map(([r, ref]) => `  --role-${r}: var(--prim-${ref});`).join("\n")}
}

/* Tier 2 · mode roles. DATA is the default; the shell root sets data-mode. */
:root,
${MODES.map((mode) => `[data-mode="${mode}"] {
${Object.entries(modeRoles[mode]).map(([r, ref]) => `  --role-${r}: var(--prim-${ref});`).join("\n")}
}`).join("\n").replace(/^:root,\n\[data-mode="DATA"\]/, ':root,\n[data-mode="DATA"]')}
`;
writeFileSync(new URL("../src/styles/colors.generated.css", import.meta.url), css);
writeFileSync(
  new URL("../src/styleguide/colors.generated.json", import.meta.url),
  JSON.stringify({ primitives: Object.fromEntries(used.map((r) => [r, primitives[r]])),
    roles, modeRoles, modes: MODES, report }, null, 2) + "\n",
);

for (const r of report) {
  if (!r.pass) console.error(`FAIL [${r.mode}] ${r.fg} on ${r.bg}: ${r.ratio} < ${r.min}`);
}
console.log(`tokens: ${used.length} primitives, ${Object.keys(roles).length} roles, ` +
  `${MODES.length} modes, ${report.length} pairs checked, ${failures} failed`);
if (failures) process.exit(1);
